spring:
  application:
    name:libraryApi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
      init:
        mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

